linters:
  disable-all: true
  enable:
    - gofmt      # Formatting issues
    - govet      # Common mistakes
    - gosimple   # Simplifications
    - ineffassign # Unused assignments

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test.go$"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gofmt
        - govet
        - gosimple
        - ineffassign
