name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4 https://github.com/actions/checkout/releases/tag/v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5 https://github.com/actions/setup-go/releases/tag/v5
        with:
          go-version: '1.20'

      - name: Download Go modules
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc  # v3 https://github.com/golangci/golangci-lint-action/releases/tag/v3
        with:
          version: v1.51.2
          skip-pkg-cache: true
          skip-build-cache: true
