name: Go Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'sharkey_test'

    - name: Test
      run: go test -v ./...
